name: Terraform Deployment

on:
  pull_request:
  push:
    branches:
      - task_1

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  TERRAFORM_VERSION: 1.9.6
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read

jobs:

  fmt:
    name: Terraform Format 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Terraform Format 
        run: terraform fmt

  terraform-init:
    name: Terraform Init
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
  
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GitHubActionRole  
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }} # Specify the version of Terraform
      
      - name: Terraform Init
        run: terraform init
